/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardValidationRouteImport } from './routes/dashboard.validation'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSpecsRouteImport } from './routes/dashboard.specs'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardMocksRouteImport } from './routes/dashboard.mocks'
import { Route as DashboardDriftRouteImport } from './routes/dashboard.drift'
import { Route as DashboardValidationWorkspaceRouteImport } from './routes/dashboard.validation.workspace'
import { Route as DashboardTeamMembersRouteImport } from './routes/dashboard.team.members'
import { Route as DashboardTeamAuditLogRouteImport } from './routes/dashboard.team.audit-log'
import { Route as DashboardSpecsNewRouteImport } from './routes/dashboard.specs.new'
import { Route as DashboardSpecsSpecIdRouteImport } from './routes/dashboard.specs.$specId'
import { Route as DashboardReportsReportIdRouteImport } from './routes/dashboard.reports.$reportId'
import { Route as DashboardMocksMockIdRouteImport } from './routes/dashboard.mocks.$mockId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardValidationRunsRunIdRouteImport } from './routes/dashboard.validation.runs.$runId'
import { Route as DashboardSpecsSpecIdCompareRouteImport } from './routes/dashboard.specs.$specId.compare'
import { Route as ApiPublicMocksMockIdRouteImport } from './routes/api/public/mocks.$mockId'
import { Route as DashboardSpecsSpecIdEndpointsEndpointIdRouteImport } from './routes/dashboard.specs.$specId.endpoints.$endpointId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidationRoute = DashboardValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpecsRoute = DashboardSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMocksRoute = DashboardMocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDriftRoute = DashboardDriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidationWorkspaceRoute =
  DashboardValidationWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => DashboardValidationRoute,
  } as any)
const DashboardTeamMembersRoute = DashboardTeamMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardTeamAuditLogRoute = DashboardTeamAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardTeamRoute,
} as any)
const DashboardSpecsNewRoute = DashboardSpecsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardSpecsRoute,
} as any)
const DashboardSpecsSpecIdRoute = DashboardSpecsSpecIdRouteImport.update({
  id: '/$specId',
  path: '/$specId',
  getParentRoute: () => DashboardSpecsRoute,
} as any)
const DashboardReportsReportIdRoute =
  DashboardReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => DashboardReportsRoute,
  } as any)
const DashboardMocksMockIdRoute = DashboardMocksMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => DashboardMocksRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardValidationRunsRunIdRoute =
  DashboardValidationRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => DashboardValidationRoute,
  } as any)
const DashboardSpecsSpecIdCompareRoute =
  DashboardSpecsSpecIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => DashboardSpecsSpecIdRoute,
  } as any)
const ApiPublicMocksMockIdRoute = ApiPublicMocksMockIdRouteImport.update({
  id: '/api/public/mocks/$mockId',
  path: '/api/public/mocks/$mockId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpecsSpecIdEndpointsEndpointIdRoute =
  DashboardSpecsSpecIdEndpointsEndpointIdRouteImport.update({
    id: '/endpoints/$endpointId',
    path: '/endpoints/$endpointId',
    getParentRoute: () => DashboardSpecsSpecIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/drift': typeof DashboardDriftRoute
  '/dashboard/mocks': typeof DashboardMocksRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/specs': typeof DashboardSpecsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/validation': typeof DashboardValidationRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/mocks/$mockId': typeof DashboardMocksMockIdRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteWithChildren
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/team/audit-log': typeof DashboardTeamAuditLogRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/api/public/mocks/$mockId': typeof ApiPublicMocksMockIdRoute
  '/dashboard/specs/$specId/compare': typeof DashboardSpecsSpecIdCompareRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/drift': typeof DashboardDriftRoute
  '/dashboard/mocks': typeof DashboardMocksRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/specs': typeof DashboardSpecsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/validation': typeof DashboardValidationRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/mocks/$mockId': typeof DashboardMocksMockIdRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteWithChildren
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/team/audit-log': typeof DashboardTeamAuditLogRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/api/public/mocks/$mockId': typeof ApiPublicMocksMockIdRoute
  '/dashboard/specs/$specId/compare': typeof DashboardSpecsSpecIdCompareRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/drift': typeof DashboardDriftRoute
  '/dashboard/mocks': typeof DashboardMocksRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/specs': typeof DashboardSpecsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRouteWithChildren
  '/dashboard/validation': typeof DashboardValidationRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/mocks/$mockId': typeof DashboardMocksMockIdRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteWithChildren
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/team/audit-log': typeof DashboardTeamAuditLogRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/api/public/mocks/$mockId': typeof ApiPublicMocksMockIdRoute
  '/dashboard/specs/$specId/compare': typeof DashboardSpecsSpecIdCompareRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/drift'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/mocks/$mockId'
    | '/dashboard/reports/$reportId'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/new'
    | '/dashboard/team/audit-log'
    | '/dashboard/team/members'
    | '/dashboard/validation/workspace'
    | '/api/public/mocks/$mockId'
    | '/dashboard/specs/$specId/compare'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/drift'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/mocks/$mockId'
    | '/dashboard/reports/$reportId'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/new'
    | '/dashboard/team/audit-log'
    | '/dashboard/team/members'
    | '/dashboard/validation/workspace'
    | '/api/public/mocks/$mockId'
    | '/dashboard/specs/$specId/compare'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/drift'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/mocks/$mockId'
    | '/dashboard/reports/$reportId'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/new'
    | '/dashboard/team/audit-log'
    | '/dashboard/team/members'
    | '/dashboard/validation/workspace'
    | '/api/public/mocks/$mockId'
    | '/dashboard/specs/$specId/compare'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicMocksMockIdRoute: typeof ApiPublicMocksMockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validation': {
      id: '/dashboard/validation'
      path: '/validation'
      fullPath: '/dashboard/validation'
      preLoaderRoute: typeof DashboardValidationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/specs': {
      id: '/dashboard/specs'
      path: '/specs'
      fullPath: '/dashboard/specs'
      preLoaderRoute: typeof DashboardSpecsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mocks': {
      id: '/dashboard/mocks'
      path: '/mocks'
      fullPath: '/dashboard/mocks'
      preLoaderRoute: typeof DashboardMocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drift': {
      id: '/dashboard/drift'
      path: '/drift'
      fullPath: '/dashboard/drift'
      preLoaderRoute: typeof DashboardDriftRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validation/workspace': {
      id: '/dashboard/validation/workspace'
      path: '/workspace'
      fullPath: '/dashboard/validation/workspace'
      preLoaderRoute: typeof DashboardValidationWorkspaceRouteImport
      parentRoute: typeof DashboardValidationRoute
    }
    '/dashboard/team/members': {
      id: '/dashboard/team/members'
      path: '/members'
      fullPath: '/dashboard/team/members'
      preLoaderRoute: typeof DashboardTeamMembersRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/team/audit-log': {
      id: '/dashboard/team/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/team/audit-log'
      preLoaderRoute: typeof DashboardTeamAuditLogRouteImport
      parentRoute: typeof DashboardTeamRoute
    }
    '/dashboard/specs/new': {
      id: '/dashboard/specs/new'
      path: '/new'
      fullPath: '/dashboard/specs/new'
      preLoaderRoute: typeof DashboardSpecsNewRouteImport
      parentRoute: typeof DashboardSpecsRoute
    }
    '/dashboard/specs/$specId': {
      id: '/dashboard/specs/$specId'
      path: '/$specId'
      fullPath: '/dashboard/specs/$specId'
      preLoaderRoute: typeof DashboardSpecsSpecIdRouteImport
      parentRoute: typeof DashboardSpecsRoute
    }
    '/dashboard/reports/$reportId': {
      id: '/dashboard/reports/$reportId'
      path: '/$reportId'
      fullPath: '/dashboard/reports/$reportId'
      preLoaderRoute: typeof DashboardReportsReportIdRouteImport
      parentRoute: typeof DashboardReportsRoute
    }
    '/dashboard/mocks/$mockId': {
      id: '/dashboard/mocks/$mockId'
      path: '/$mockId'
      fullPath: '/dashboard/mocks/$mockId'
      preLoaderRoute: typeof DashboardMocksMockIdRouteImport
      parentRoute: typeof DashboardMocksRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/validation/runs/$runId': {
      id: '/dashboard/validation/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/dashboard/validation/runs/$runId'
      preLoaderRoute: typeof DashboardValidationRunsRunIdRouteImport
      parentRoute: typeof DashboardValidationRoute
    }
    '/dashboard/specs/$specId/compare': {
      id: '/dashboard/specs/$specId/compare'
      path: '/compare'
      fullPath: '/dashboard/specs/$specId/compare'
      preLoaderRoute: typeof DashboardSpecsSpecIdCompareRouteImport
      parentRoute: typeof DashboardSpecsSpecIdRoute
    }
    '/api/public/mocks/$mockId': {
      id: '/api/public/mocks/$mockId'
      path: '/api/public/mocks/$mockId'
      fullPath: '/api/public/mocks/$mockId'
      preLoaderRoute: typeof ApiPublicMocksMockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/specs/$specId/endpoints/$endpointId': {
      id: '/dashboard/specs/$specId/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/dashboard/specs/$specId/endpoints/$endpointId'
      preLoaderRoute: typeof DashboardSpecsSpecIdEndpointsEndpointIdRouteImport
      parentRoute: typeof DashboardSpecsSpecIdRoute
    }
  }
}

interface DashboardMocksRouteChildren {
  DashboardMocksMockIdRoute: typeof DashboardMocksMockIdRoute
}

const DashboardMocksRouteChildren: DashboardMocksRouteChildren = {
  DashboardMocksMockIdRoute: DashboardMocksMockIdRoute,
}

const DashboardMocksRouteWithChildren = DashboardMocksRoute._addFileChildren(
  DashboardMocksRouteChildren,
)

interface DashboardReportsRouteChildren {
  DashboardReportsReportIdRoute: typeof DashboardReportsReportIdRoute
}

const DashboardReportsRouteChildren: DashboardReportsRouteChildren = {
  DashboardReportsReportIdRoute: DashboardReportsReportIdRoute,
}

const DashboardReportsRouteWithChildren =
  DashboardReportsRoute._addFileChildren(DashboardReportsRouteChildren)

interface DashboardSpecsSpecIdRouteChildren {
  DashboardSpecsSpecIdCompareRoute: typeof DashboardSpecsSpecIdCompareRoute
  DashboardSpecsSpecIdEndpointsEndpointIdRoute: typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}

const DashboardSpecsSpecIdRouteChildren: DashboardSpecsSpecIdRouteChildren = {
  DashboardSpecsSpecIdCompareRoute: DashboardSpecsSpecIdCompareRoute,
  DashboardSpecsSpecIdEndpointsEndpointIdRoute:
    DashboardSpecsSpecIdEndpointsEndpointIdRoute,
}

const DashboardSpecsSpecIdRouteWithChildren =
  DashboardSpecsSpecIdRoute._addFileChildren(DashboardSpecsSpecIdRouteChildren)

interface DashboardSpecsRouteChildren {
  DashboardSpecsSpecIdRoute: typeof DashboardSpecsSpecIdRouteWithChildren
  DashboardSpecsNewRoute: typeof DashboardSpecsNewRoute
}

const DashboardSpecsRouteChildren: DashboardSpecsRouteChildren = {
  DashboardSpecsSpecIdRoute: DashboardSpecsSpecIdRouteWithChildren,
  DashboardSpecsNewRoute: DashboardSpecsNewRoute,
}

const DashboardSpecsRouteWithChildren = DashboardSpecsRoute._addFileChildren(
  DashboardSpecsRouteChildren,
)

interface DashboardTeamRouteChildren {
  DashboardTeamAuditLogRoute: typeof DashboardTeamAuditLogRoute
  DashboardTeamMembersRoute: typeof DashboardTeamMembersRoute
}

const DashboardTeamRouteChildren: DashboardTeamRouteChildren = {
  DashboardTeamAuditLogRoute: DashboardTeamAuditLogRoute,
  DashboardTeamMembersRoute: DashboardTeamMembersRoute,
}

const DashboardTeamRouteWithChildren = DashboardTeamRoute._addFileChildren(
  DashboardTeamRouteChildren,
)

interface DashboardValidationRouteChildren {
  DashboardValidationWorkspaceRoute: typeof DashboardValidationWorkspaceRoute
  DashboardValidationRunsRunIdRoute: typeof DashboardValidationRunsRunIdRoute
}

const DashboardValidationRouteChildren: DashboardValidationRouteChildren = {
  DashboardValidationWorkspaceRoute: DashboardValidationWorkspaceRoute,
  DashboardValidationRunsRunIdRoute: DashboardValidationRunsRunIdRoute,
}

const DashboardValidationRouteWithChildren =
  DashboardValidationRoute._addFileChildren(DashboardValidationRouteChildren)

interface DashboardRouteChildren {
  DashboardDriftRoute: typeof DashboardDriftRoute
  DashboardMocksRoute: typeof DashboardMocksRouteWithChildren
  DashboardReportsRoute: typeof DashboardReportsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpecsRoute: typeof DashboardSpecsRouteWithChildren
  DashboardTeamRoute: typeof DashboardTeamRouteWithChildren
  DashboardValidationRoute: typeof DashboardValidationRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDriftRoute: DashboardDriftRoute,
  DashboardMocksRoute: DashboardMocksRouteWithChildren,
  DashboardReportsRoute: DashboardReportsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpecsRoute: DashboardSpecsRouteWithChildren,
  DashboardTeamRoute: DashboardTeamRouteWithChildren,
  DashboardValidationRoute: DashboardValidationRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicMocksMockIdRoute: ApiPublicMocksMockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
