/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardValidationRouteImport } from './routes/dashboard.validation'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSpecsRouteImport } from './routes/dashboard.specs'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardMocksRouteImport } from './routes/dashboard.mocks'
import { Route as DashboardValidationWorkspaceRouteImport } from './routes/dashboard.validation.workspace'
import { Route as DashboardSpecsNewRouteImport } from './routes/dashboard.specs.new'
import { Route as DashboardSpecsSpecIdRouteImport } from './routes/dashboard.specs.$specId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardValidationRunsRunIdRouteImport } from './routes/dashboard.validation.runs.$runId'
import { Route as DashboardSpecsSpecIdEndpointsEndpointIdRouteImport } from './routes/dashboard.specs.$specId.endpoints.$endpointId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardValidationRoute = DashboardValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpecsRoute = DashboardSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMocksRoute = DashboardMocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidationWorkspaceRoute =
  DashboardValidationWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => DashboardValidationRoute,
  } as any)
const DashboardSpecsNewRoute = DashboardSpecsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardSpecsRoute,
} as any)
const DashboardSpecsSpecIdRoute = DashboardSpecsSpecIdRouteImport.update({
  id: '/$specId',
  path: '/$specId',
  getParentRoute: () => DashboardSpecsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardValidationRunsRunIdRoute =
  DashboardValidationRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => DashboardValidationRoute,
  } as any)
const DashboardSpecsSpecIdEndpointsEndpointIdRoute =
  DashboardSpecsSpecIdEndpointsEndpointIdRouteImport.update({
    id: '/endpoints/$endpointId',
    path: '/endpoints/$endpointId',
    getParentRoute: () => DashboardSpecsSpecIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/mocks': typeof DashboardMocksRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/specs': typeof DashboardSpecsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/validation': typeof DashboardValidationRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteWithChildren
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/mocks': typeof DashboardMocksRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/specs': typeof DashboardSpecsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/validation': typeof DashboardValidationRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteWithChildren
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/mocks': typeof DashboardMocksRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/specs': typeof DashboardSpecsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/validation': typeof DashboardValidationRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteWithChildren
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/api/auth/$'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/new'
    | '/dashboard/validation/workspace'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/api/auth/$'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/new'
    | '/dashboard/validation/workspace'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/api/auth/$'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/new'
    | '/dashboard/validation/workspace'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/validation': {
      id: '/dashboard/validation'
      path: '/validation'
      fullPath: '/dashboard/validation'
      preLoaderRoute: typeof DashboardValidationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/specs': {
      id: '/dashboard/specs'
      path: '/specs'
      fullPath: '/dashboard/specs'
      preLoaderRoute: typeof DashboardSpecsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mocks': {
      id: '/dashboard/mocks'
      path: '/mocks'
      fullPath: '/dashboard/mocks'
      preLoaderRoute: typeof DashboardMocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validation/workspace': {
      id: '/dashboard/validation/workspace'
      path: '/workspace'
      fullPath: '/dashboard/validation/workspace'
      preLoaderRoute: typeof DashboardValidationWorkspaceRouteImport
      parentRoute: typeof DashboardValidationRoute
    }
    '/dashboard/specs/new': {
      id: '/dashboard/specs/new'
      path: '/new'
      fullPath: '/dashboard/specs/new'
      preLoaderRoute: typeof DashboardSpecsNewRouteImport
      parentRoute: typeof DashboardSpecsRoute
    }
    '/dashboard/specs/$specId': {
      id: '/dashboard/specs/$specId'
      path: '/$specId'
      fullPath: '/dashboard/specs/$specId'
      preLoaderRoute: typeof DashboardSpecsSpecIdRouteImport
      parentRoute: typeof DashboardSpecsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/validation/runs/$runId': {
      id: '/dashboard/validation/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/dashboard/validation/runs/$runId'
      preLoaderRoute: typeof DashboardValidationRunsRunIdRouteImport
      parentRoute: typeof DashboardValidationRoute
    }
    '/dashboard/specs/$specId/endpoints/$endpointId': {
      id: '/dashboard/specs/$specId/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/dashboard/specs/$specId/endpoints/$endpointId'
      preLoaderRoute: typeof DashboardSpecsSpecIdEndpointsEndpointIdRouteImport
      parentRoute: typeof DashboardSpecsSpecIdRoute
    }
  }
}

interface DashboardSpecsSpecIdRouteChildren {
  DashboardSpecsSpecIdEndpointsEndpointIdRoute: typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}

const DashboardSpecsSpecIdRouteChildren: DashboardSpecsSpecIdRouteChildren = {
  DashboardSpecsSpecIdEndpointsEndpointIdRoute:
    DashboardSpecsSpecIdEndpointsEndpointIdRoute,
}

const DashboardSpecsSpecIdRouteWithChildren =
  DashboardSpecsSpecIdRoute._addFileChildren(DashboardSpecsSpecIdRouteChildren)

interface DashboardSpecsRouteChildren {
  DashboardSpecsSpecIdRoute: typeof DashboardSpecsSpecIdRouteWithChildren
  DashboardSpecsNewRoute: typeof DashboardSpecsNewRoute
}

const DashboardSpecsRouteChildren: DashboardSpecsRouteChildren = {
  DashboardSpecsSpecIdRoute: DashboardSpecsSpecIdRouteWithChildren,
  DashboardSpecsNewRoute: DashboardSpecsNewRoute,
}

const DashboardSpecsRouteWithChildren = DashboardSpecsRoute._addFileChildren(
  DashboardSpecsRouteChildren,
)

interface DashboardValidationRouteChildren {
  DashboardValidationWorkspaceRoute: typeof DashboardValidationWorkspaceRoute
  DashboardValidationRunsRunIdRoute: typeof DashboardValidationRunsRunIdRoute
}

const DashboardValidationRouteChildren: DashboardValidationRouteChildren = {
  DashboardValidationWorkspaceRoute: DashboardValidationWorkspaceRoute,
  DashboardValidationRunsRunIdRoute: DashboardValidationRunsRunIdRoute,
}

const DashboardValidationRouteWithChildren =
  DashboardValidationRoute._addFileChildren(DashboardValidationRouteChildren)

interface DashboardRouteChildren {
  DashboardMocksRoute: typeof DashboardMocksRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpecsRoute: typeof DashboardSpecsRouteWithChildren
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardValidationRoute: typeof DashboardValidationRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMocksRoute: DashboardMocksRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpecsRoute: DashboardSpecsRouteWithChildren,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardValidationRoute: DashboardValidationRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
