/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R2faRouteImport } from './routes/2fa'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as DashboardValidationRouteRouteImport } from './routes/dashboard/validation/route'
import { Route as DashboardTeamRouteRouteImport } from './routes/dashboard/team/route'
import { Route as DashboardSpecsRouteRouteImport } from './routes/dashboard/specs/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardReportsRouteRouteImport } from './routes/dashboard/reports/route'
import { Route as DashboardMocksRouteRouteImport } from './routes/dashboard/mocks/route'
import { Route as DashboardDriftRouteRouteImport } from './routes/dashboard/drift/route'
import { Route as DashboardValidationIndexRouteImport } from './routes/dashboard/validation/index'
import { Route as DashboardSpecsIndexRouteImport } from './routes/dashboard/specs/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardMocksIndexRouteImport } from './routes/dashboard/mocks/index'
import { Route as DashboardDriftIndexRouteImport } from './routes/dashboard/drift/index'
import { Route as DashboardValidationWorkspaceRouteImport } from './routes/dashboard/validation/workspace'
import { Route as DashboardTeamMembersRouteImport } from './routes/dashboard/team/members'
import { Route as DashboardTeamInvitationsRouteImport } from './routes/dashboard/team/invitations'
import { Route as DashboardTeamAuditLogRouteImport } from './routes/dashboard/team/audit-log'
import { Route as DashboardSpecsNewRouteImport } from './routes/dashboard/specs/new'
import { Route as DashboardSettingsWorkspaceRouteImport } from './routes/dashboard/settings/workspace'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsApiKeysRouteImport } from './routes/dashboard/settings/api-keys'
import { Route as DashboardSettingsAccountRouteImport } from './routes/dashboard/settings/account'
import { Route as DashboardReportsReportIdRouteImport } from './routes/dashboard/reports/$reportId'
import { Route as DashboardMocksMockIdRouteImport } from './routes/dashboard/mocks/$mockId'
import { Route as DashboardDriftNotificationsRouteImport } from './routes/dashboard/drift/notifications'
import { Route as DashboardDriftMonitoredSpecsRouteImport } from './routes/dashboard/drift/monitored-specs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSpecsSpecIdRouteRouteImport } from './routes/dashboard/specs/$specId/route'
import { Route as DashboardSpecsSpecIdIndexRouteImport } from './routes/dashboard/specs/$specId/index'
import { Route as DashboardValidationRunsRunIdRouteImport } from './routes/dashboard/validation/runs/$runId'
import { Route as DashboardSpecsSpecIdCompareRouteImport } from './routes/dashboard/specs/$specId/compare'
import { Route as ApiPublicMocksMockIdRouteImport } from './routes/api/public/mocks/$mockId'
import { Route as DashboardSpecsSpecIdEndpointsEndpointIdRouteImport } from './routes/dashboard/specs/$specId/endpoints/$endpointId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faRoute = R2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardValidationRouteRoute =
  DashboardValidationRouteRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTeamRouteRoute = DashboardTeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSpecsRouteRoute = DashboardSpecsRouteRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsRouteRoute = DashboardReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMocksRouteRoute = DashboardMocksRouteRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDriftRouteRoute = DashboardDriftRouteRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardValidationIndexRoute =
  DashboardValidationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardValidationRouteRoute,
  } as any)
const DashboardSpecsIndexRoute = DashboardSpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSpecsRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardReportsRouteRoute,
} as any)
const DashboardMocksIndexRoute = DashboardMocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMocksRouteRoute,
} as any)
const DashboardDriftIndexRoute = DashboardDriftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDriftRouteRoute,
} as any)
const DashboardValidationWorkspaceRoute =
  DashboardValidationWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => DashboardValidationRouteRoute,
  } as any)
const DashboardTeamMembersRoute = DashboardTeamMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardTeamRouteRoute,
} as any)
const DashboardTeamInvitationsRoute =
  DashboardTeamInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => DashboardTeamRouteRoute,
  } as any)
const DashboardTeamAuditLogRoute = DashboardTeamAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardTeamRouteRoute,
} as any)
const DashboardSpecsNewRoute = DashboardSpecsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardSpecsRouteRoute,
} as any)
const DashboardSettingsWorkspaceRoute =
  DashboardSettingsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardReportsReportIdRoute =
  DashboardReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => DashboardReportsRouteRoute,
  } as any)
const DashboardMocksMockIdRoute = DashboardMocksMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => DashboardMocksRouteRoute,
} as any)
const DashboardDriftNotificationsRoute =
  DashboardDriftNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardDriftRouteRoute,
  } as any)
const DashboardDriftMonitoredSpecsRoute =
  DashboardDriftMonitoredSpecsRouteImport.update({
    id: '/monitored-specs',
    path: '/monitored-specs',
    getParentRoute: () => DashboardDriftRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpecsSpecIdRouteRoute =
  DashboardSpecsSpecIdRouteRouteImport.update({
    id: '/$specId',
    path: '/$specId',
    getParentRoute: () => DashboardSpecsRouteRoute,
  } as any)
const DashboardSpecsSpecIdIndexRoute =
  DashboardSpecsSpecIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSpecsSpecIdRouteRoute,
  } as any)
const DashboardValidationRunsRunIdRoute =
  DashboardValidationRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => DashboardValidationRouteRoute,
  } as any)
const DashboardSpecsSpecIdCompareRoute =
  DashboardSpecsSpecIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => DashboardSpecsSpecIdRouteRoute,
  } as any)
const ApiPublicMocksMockIdRoute = ApiPublicMocksMockIdRouteImport.update({
  id: '/api/public/mocks/$mockId',
  path: '/api/public/mocks/$mockId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpecsSpecIdEndpointsEndpointIdRoute =
  DashboardSpecsSpecIdEndpointsEndpointIdRouteImport.update({
    id: '/endpoints/$endpointId',
    path: '/endpoints/$endpointId',
    getParentRoute: () => DashboardSpecsSpecIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/2fa': typeof R2faRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/drift': typeof DashboardDriftRouteRouteWithChildren
  '/dashboard/mocks': typeof DashboardMocksRouteRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/specs': typeof DashboardSpecsRouteRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRouteRouteWithChildren
  '/dashboard/validation': typeof DashboardValidationRouteRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/drift/monitored-specs': typeof DashboardDriftMonitoredSpecsRoute
  '/dashboard/drift/notifications': typeof DashboardDriftNotificationsRoute
  '/dashboard/mocks/$mockId': typeof DashboardMocksMockIdRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/team/audit-log': typeof DashboardTeamAuditLogRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/dashboard/drift/': typeof DashboardDriftIndexRoute
  '/dashboard/mocks/': typeof DashboardMocksIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/specs/': typeof DashboardSpecsIndexRoute
  '/dashboard/validation/': typeof DashboardValidationIndexRoute
  '/api/public/mocks/$mockId': typeof ApiPublicMocksMockIdRoute
  '/dashboard/specs/$specId/compare': typeof DashboardSpecsSpecIdCompareRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/': typeof DashboardSpecsSpecIdIndexRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2fa': typeof R2faRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/team': typeof DashboardTeamRouteRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/drift/monitored-specs': typeof DashboardDriftMonitoredSpecsRoute
  '/dashboard/drift/notifications': typeof DashboardDriftNotificationsRoute
  '/dashboard/mocks/$mockId': typeof DashboardMocksMockIdRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/team/audit-log': typeof DashboardTeamAuditLogRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/dashboard/drift': typeof DashboardDriftIndexRoute
  '/dashboard/mocks': typeof DashboardMocksIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/specs': typeof DashboardSpecsIndexRoute
  '/dashboard/validation': typeof DashboardValidationIndexRoute
  '/api/public/mocks/$mockId': typeof ApiPublicMocksMockIdRoute
  '/dashboard/specs/$specId/compare': typeof DashboardSpecsSpecIdCompareRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdIndexRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/2fa': typeof R2faRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/drift': typeof DashboardDriftRouteRouteWithChildren
  '/dashboard/mocks': typeof DashboardMocksRouteRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/specs': typeof DashboardSpecsRouteRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRouteRouteWithChildren
  '/dashboard/validation': typeof DashboardValidationRouteRouteWithChildren
  '/api/inngest': typeof ApiInngestRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/specs/$specId': typeof DashboardSpecsSpecIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/drift/monitored-specs': typeof DashboardDriftMonitoredSpecsRoute
  '/dashboard/drift/notifications': typeof DashboardDriftNotificationsRoute
  '/dashboard/mocks/$mockId': typeof DashboardMocksMockIdRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/api-keys': typeof DashboardSettingsApiKeysRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/workspace': typeof DashboardSettingsWorkspaceRoute
  '/dashboard/specs/new': typeof DashboardSpecsNewRoute
  '/dashboard/team/audit-log': typeof DashboardTeamAuditLogRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/validation/workspace': typeof DashboardValidationWorkspaceRoute
  '/dashboard/drift/': typeof DashboardDriftIndexRoute
  '/dashboard/mocks/': typeof DashboardMocksIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/specs/': typeof DashboardSpecsIndexRoute
  '/dashboard/validation/': typeof DashboardValidationIndexRoute
  '/api/public/mocks/$mockId': typeof ApiPublicMocksMockIdRoute
  '/dashboard/specs/$specId/compare': typeof DashboardSpecsSpecIdCompareRoute
  '/dashboard/validation/runs/$runId': typeof DashboardValidationRunsRunIdRoute
  '/dashboard/specs/$specId/': typeof DashboardSpecsSpecIdIndexRoute
  '/dashboard/specs/$specId/endpoints/$endpointId': typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/2fa'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard/drift'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/api/inngest'
    | '/dashboard/'
    | '/dashboard/specs/$specId'
    | '/api/auth/$'
    | '/dashboard/drift/monitored-specs'
    | '/dashboard/drift/notifications'
    | '/dashboard/mocks/$mockId'
    | '/dashboard/reports/$reportId'
    | '/dashboard/settings/account'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/security'
    | '/dashboard/settings/workspace'
    | '/dashboard/specs/new'
    | '/dashboard/team/audit-log'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/validation/workspace'
    | '/dashboard/drift/'
    | '/dashboard/mocks/'
    | '/dashboard/reports/'
    | '/dashboard/settings/'
    | '/dashboard/specs/'
    | '/dashboard/validation/'
    | '/api/public/mocks/$mockId'
    | '/dashboard/specs/$specId/compare'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2fa'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard/team'
    | '/api/inngest'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/drift/monitored-specs'
    | '/dashboard/drift/notifications'
    | '/dashboard/mocks/$mockId'
    | '/dashboard/reports/$reportId'
    | '/dashboard/settings/account'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/security'
    | '/dashboard/settings/workspace'
    | '/dashboard/specs/new'
    | '/dashboard/team/audit-log'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/validation/workspace'
    | '/dashboard/drift'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/validation'
    | '/api/public/mocks/$mockId'
    | '/dashboard/specs/$specId/compare'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/2fa'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard/drift'
    | '/dashboard/mocks'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/specs'
    | '/dashboard/team'
    | '/dashboard/validation'
    | '/api/inngest'
    | '/dashboard/'
    | '/dashboard/specs/$specId'
    | '/api/auth/$'
    | '/dashboard/drift/monitored-specs'
    | '/dashboard/drift/notifications'
    | '/dashboard/mocks/$mockId'
    | '/dashboard/reports/$reportId'
    | '/dashboard/settings/account'
    | '/dashboard/settings/api-keys'
    | '/dashboard/settings/security'
    | '/dashboard/settings/workspace'
    | '/dashboard/specs/new'
    | '/dashboard/team/audit-log'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/validation/workspace'
    | '/dashboard/drift/'
    | '/dashboard/mocks/'
    | '/dashboard/reports/'
    | '/dashboard/settings/'
    | '/dashboard/specs/'
    | '/dashboard/validation/'
    | '/api/public/mocks/$mockId'
    | '/dashboard/specs/$specId/compare'
    | '/dashboard/validation/runs/$runId'
    | '/dashboard/specs/$specId/'
    | '/dashboard/specs/$specId/endpoints/$endpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  R2faRoute: typeof R2faRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicMocksMockIdRoute: typeof ApiPublicMocksMockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa': {
      id: '/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof R2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/validation': {
      id: '/dashboard/validation'
      path: '/validation'
      fullPath: '/dashboard/validation'
      preLoaderRoute: typeof DashboardValidationRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/specs': {
      id: '/dashboard/specs'
      path: '/specs'
      fullPath: '/dashboard/specs'
      preLoaderRoute: typeof DashboardSpecsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/mocks': {
      id: '/dashboard/mocks'
      path: '/mocks'
      fullPath: '/dashboard/mocks'
      preLoaderRoute: typeof DashboardMocksRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/drift': {
      id: '/dashboard/drift'
      path: '/drift'
      fullPath: '/dashboard/drift'
      preLoaderRoute: typeof DashboardDriftRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/validation/': {
      id: '/dashboard/validation/'
      path: '/'
      fullPath: '/dashboard/validation/'
      preLoaderRoute: typeof DashboardValidationIndexRouteImport
      parentRoute: typeof DashboardValidationRouteRoute
    }
    '/dashboard/specs/': {
      id: '/dashboard/specs/'
      path: '/'
      fullPath: '/dashboard/specs/'
      preLoaderRoute: typeof DashboardSpecsIndexRouteImport
      parentRoute: typeof DashboardSpecsRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardReportsRouteRoute
    }
    '/dashboard/mocks/': {
      id: '/dashboard/mocks/'
      path: '/'
      fullPath: '/dashboard/mocks/'
      preLoaderRoute: typeof DashboardMocksIndexRouteImport
      parentRoute: typeof DashboardMocksRouteRoute
    }
    '/dashboard/drift/': {
      id: '/dashboard/drift/'
      path: '/'
      fullPath: '/dashboard/drift/'
      preLoaderRoute: typeof DashboardDriftIndexRouteImport
      parentRoute: typeof DashboardDriftRouteRoute
    }
    '/dashboard/validation/workspace': {
      id: '/dashboard/validation/workspace'
      path: '/workspace'
      fullPath: '/dashboard/validation/workspace'
      preLoaderRoute: typeof DashboardValidationWorkspaceRouteImport
      parentRoute: typeof DashboardValidationRouteRoute
    }
    '/dashboard/team/members': {
      id: '/dashboard/team/members'
      path: '/members'
      fullPath: '/dashboard/team/members'
      preLoaderRoute: typeof DashboardTeamMembersRouteImport
      parentRoute: typeof DashboardTeamRouteRoute
    }
    '/dashboard/team/invitations': {
      id: '/dashboard/team/invitations'
      path: '/invitations'
      fullPath: '/dashboard/team/invitations'
      preLoaderRoute: typeof DashboardTeamInvitationsRouteImport
      parentRoute: typeof DashboardTeamRouteRoute
    }
    '/dashboard/team/audit-log': {
      id: '/dashboard/team/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/team/audit-log'
      preLoaderRoute: typeof DashboardTeamAuditLogRouteImport
      parentRoute: typeof DashboardTeamRouteRoute
    }
    '/dashboard/specs/new': {
      id: '/dashboard/specs/new'
      path: '/new'
      fullPath: '/dashboard/specs/new'
      preLoaderRoute: typeof DashboardSpecsNewRouteImport
      parentRoute: typeof DashboardSpecsRouteRoute
    }
    '/dashboard/settings/workspace': {
      id: '/dashboard/settings/workspace'
      path: '/workspace'
      fullPath: '/dashboard/settings/workspace'
      preLoaderRoute: typeof DashboardSettingsWorkspaceRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/api-keys': {
      id: '/dashboard/settings/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/settings/api-keys'
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/reports/$reportId': {
      id: '/dashboard/reports/$reportId'
      path: '/$reportId'
      fullPath: '/dashboard/reports/$reportId'
      preLoaderRoute: typeof DashboardReportsReportIdRouteImport
      parentRoute: typeof DashboardReportsRouteRoute
    }
    '/dashboard/mocks/$mockId': {
      id: '/dashboard/mocks/$mockId'
      path: '/$mockId'
      fullPath: '/dashboard/mocks/$mockId'
      preLoaderRoute: typeof DashboardMocksMockIdRouteImport
      parentRoute: typeof DashboardMocksRouteRoute
    }
    '/dashboard/drift/notifications': {
      id: '/dashboard/drift/notifications'
      path: '/notifications'
      fullPath: '/dashboard/drift/notifications'
      preLoaderRoute: typeof DashboardDriftNotificationsRouteImport
      parentRoute: typeof DashboardDriftRouteRoute
    }
    '/dashboard/drift/monitored-specs': {
      id: '/dashboard/drift/monitored-specs'
      path: '/monitored-specs'
      fullPath: '/dashboard/drift/monitored-specs'
      preLoaderRoute: typeof DashboardDriftMonitoredSpecsRouteImport
      parentRoute: typeof DashboardDriftRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/specs/$specId': {
      id: '/dashboard/specs/$specId'
      path: '/$specId'
      fullPath: '/dashboard/specs/$specId'
      preLoaderRoute: typeof DashboardSpecsSpecIdRouteRouteImport
      parentRoute: typeof DashboardSpecsRouteRoute
    }
    '/dashboard/specs/$specId/': {
      id: '/dashboard/specs/$specId/'
      path: '/'
      fullPath: '/dashboard/specs/$specId/'
      preLoaderRoute: typeof DashboardSpecsSpecIdIndexRouteImport
      parentRoute: typeof DashboardSpecsSpecIdRouteRoute
    }
    '/dashboard/validation/runs/$runId': {
      id: '/dashboard/validation/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/dashboard/validation/runs/$runId'
      preLoaderRoute: typeof DashboardValidationRunsRunIdRouteImport
      parentRoute: typeof DashboardValidationRouteRoute
    }
    '/dashboard/specs/$specId/compare': {
      id: '/dashboard/specs/$specId/compare'
      path: '/compare'
      fullPath: '/dashboard/specs/$specId/compare'
      preLoaderRoute: typeof DashboardSpecsSpecIdCompareRouteImport
      parentRoute: typeof DashboardSpecsSpecIdRouteRoute
    }
    '/api/public/mocks/$mockId': {
      id: '/api/public/mocks/$mockId'
      path: '/api/public/mocks/$mockId'
      fullPath: '/api/public/mocks/$mockId'
      preLoaderRoute: typeof ApiPublicMocksMockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/specs/$specId/endpoints/$endpointId': {
      id: '/dashboard/specs/$specId/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/dashboard/specs/$specId/endpoints/$endpointId'
      preLoaderRoute: typeof DashboardSpecsSpecIdEndpointsEndpointIdRouteImport
      parentRoute: typeof DashboardSpecsSpecIdRouteRoute
    }
  }
}

interface DashboardDriftRouteRouteChildren {
  DashboardDriftMonitoredSpecsRoute: typeof DashboardDriftMonitoredSpecsRoute
  DashboardDriftNotificationsRoute: typeof DashboardDriftNotificationsRoute
  DashboardDriftIndexRoute: typeof DashboardDriftIndexRoute
}

const DashboardDriftRouteRouteChildren: DashboardDriftRouteRouteChildren = {
  DashboardDriftMonitoredSpecsRoute: DashboardDriftMonitoredSpecsRoute,
  DashboardDriftNotificationsRoute: DashboardDriftNotificationsRoute,
  DashboardDriftIndexRoute: DashboardDriftIndexRoute,
}

const DashboardDriftRouteRouteWithChildren =
  DashboardDriftRouteRoute._addFileChildren(DashboardDriftRouteRouteChildren)

interface DashboardMocksRouteRouteChildren {
  DashboardMocksMockIdRoute: typeof DashboardMocksMockIdRoute
  DashboardMocksIndexRoute: typeof DashboardMocksIndexRoute
}

const DashboardMocksRouteRouteChildren: DashboardMocksRouteRouteChildren = {
  DashboardMocksMockIdRoute: DashboardMocksMockIdRoute,
  DashboardMocksIndexRoute: DashboardMocksIndexRoute,
}

const DashboardMocksRouteRouteWithChildren =
  DashboardMocksRouteRoute._addFileChildren(DashboardMocksRouteRouteChildren)

interface DashboardReportsRouteRouteChildren {
  DashboardReportsReportIdRoute: typeof DashboardReportsReportIdRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
}

const DashboardReportsRouteRouteChildren: DashboardReportsRouteRouteChildren = {
  DashboardReportsReportIdRoute: DashboardReportsReportIdRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
}

const DashboardReportsRouteRouteWithChildren =
  DashboardReportsRouteRoute._addFileChildren(
    DashboardReportsRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsWorkspaceRoute: typeof DashboardSettingsWorkspaceRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
    DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
    DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
    DashboardSettingsWorkspaceRoute: DashboardSettingsWorkspaceRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardSpecsSpecIdRouteRouteChildren {
  DashboardSpecsSpecIdCompareRoute: typeof DashboardSpecsSpecIdCompareRoute
  DashboardSpecsSpecIdIndexRoute: typeof DashboardSpecsSpecIdIndexRoute
  DashboardSpecsSpecIdEndpointsEndpointIdRoute: typeof DashboardSpecsSpecIdEndpointsEndpointIdRoute
}

const DashboardSpecsSpecIdRouteRouteChildren: DashboardSpecsSpecIdRouteRouteChildren =
  {
    DashboardSpecsSpecIdCompareRoute: DashboardSpecsSpecIdCompareRoute,
    DashboardSpecsSpecIdIndexRoute: DashboardSpecsSpecIdIndexRoute,
    DashboardSpecsSpecIdEndpointsEndpointIdRoute:
      DashboardSpecsSpecIdEndpointsEndpointIdRoute,
  }

const DashboardSpecsSpecIdRouteRouteWithChildren =
  DashboardSpecsSpecIdRouteRoute._addFileChildren(
    DashboardSpecsSpecIdRouteRouteChildren,
  )

interface DashboardSpecsRouteRouteChildren {
  DashboardSpecsSpecIdRouteRoute: typeof DashboardSpecsSpecIdRouteRouteWithChildren
  DashboardSpecsNewRoute: typeof DashboardSpecsNewRoute
  DashboardSpecsIndexRoute: typeof DashboardSpecsIndexRoute
}

const DashboardSpecsRouteRouteChildren: DashboardSpecsRouteRouteChildren = {
  DashboardSpecsSpecIdRouteRoute: DashboardSpecsSpecIdRouteRouteWithChildren,
  DashboardSpecsNewRoute: DashboardSpecsNewRoute,
  DashboardSpecsIndexRoute: DashboardSpecsIndexRoute,
}

const DashboardSpecsRouteRouteWithChildren =
  DashboardSpecsRouteRoute._addFileChildren(DashboardSpecsRouteRouteChildren)

interface DashboardTeamRouteRouteChildren {
  DashboardTeamAuditLogRoute: typeof DashboardTeamAuditLogRoute
  DashboardTeamInvitationsRoute: typeof DashboardTeamInvitationsRoute
  DashboardTeamMembersRoute: typeof DashboardTeamMembersRoute
}

const DashboardTeamRouteRouteChildren: DashboardTeamRouteRouteChildren = {
  DashboardTeamAuditLogRoute: DashboardTeamAuditLogRoute,
  DashboardTeamInvitationsRoute: DashboardTeamInvitationsRoute,
  DashboardTeamMembersRoute: DashboardTeamMembersRoute,
}

const DashboardTeamRouteRouteWithChildren =
  DashboardTeamRouteRoute._addFileChildren(DashboardTeamRouteRouteChildren)

interface DashboardValidationRouteRouteChildren {
  DashboardValidationWorkspaceRoute: typeof DashboardValidationWorkspaceRoute
  DashboardValidationIndexRoute: typeof DashboardValidationIndexRoute
  DashboardValidationRunsRunIdRoute: typeof DashboardValidationRunsRunIdRoute
}

const DashboardValidationRouteRouteChildren: DashboardValidationRouteRouteChildren =
  {
    DashboardValidationWorkspaceRoute: DashboardValidationWorkspaceRoute,
    DashboardValidationIndexRoute: DashboardValidationIndexRoute,
    DashboardValidationRunsRunIdRoute: DashboardValidationRunsRunIdRoute,
  }

const DashboardValidationRouteRouteWithChildren =
  DashboardValidationRouteRoute._addFileChildren(
    DashboardValidationRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDriftRouteRoute: typeof DashboardDriftRouteRouteWithChildren
  DashboardMocksRouteRoute: typeof DashboardMocksRouteRouteWithChildren
  DashboardReportsRouteRoute: typeof DashboardReportsRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardSpecsRouteRoute: typeof DashboardSpecsRouteRouteWithChildren
  DashboardTeamRouteRoute: typeof DashboardTeamRouteRouteWithChildren
  DashboardValidationRouteRoute: typeof DashboardValidationRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDriftRouteRoute: DashboardDriftRouteRouteWithChildren,
  DashboardMocksRouteRoute: DashboardMocksRouteRouteWithChildren,
  DashboardReportsRouteRoute: DashboardReportsRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardSpecsRouteRoute: DashboardSpecsRouteRouteWithChildren,
  DashboardTeamRouteRoute: DashboardTeamRouteRouteWithChildren,
  DashboardValidationRouteRoute: DashboardValidationRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  R2faRoute: R2faRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicMocksMockIdRoute: ApiPublicMocksMockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
